"""initial schema

Revision ID: 771017ecfbb2
Revises: 370aefcd8991
Create Date: 2026-03-31 22:25:01.417212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771017ecfbb2'
down_revision = '370aefcd8991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_intent_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.drop_column('total_amount')
        batch_op.drop_column('payment_intent_id')

    # ### end Alembic commands ###
