"""add onboarding fields

Revision ID: f4ac9f8424f8
Revises: 935bb3ecdb80
Create Date: 2026-02-12 23:53:39.753860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ac9f8424f8'
down_revision = '935bb3ecdb80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topStyle', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bottomStyle', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('height', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('bottomStyle')
        batch_op.drop_column('topStyle')

    op.drop_table('waitlist_email')
    # ### end Alembic commands ###
